[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "ljudladan"
version = "0.1.2"
description = "Sound sensitivity tool with custom sound profiles"
license = "GPL-3.0-or-later"

[tool.setuptools.packages.find]
where = ["."]
